# Bias
-Bias is the simplifying assumption made by the model to make the target function easier to approximate

# Variance
-Variance is the amount that the estimate of the target fuction will change given different training data

## Overfitting
-Good performance on the training data.low bias and high variance will get the occurance of overfitting


 ## Underfitting
-poor performance on the training data and poor generalization to other data. 
-High bias and low variance

# Ridge regression
-squared magnitude of coefficient as penalty to the loss function.

# # Lasso Regression
-(Least absolute shrinkage and selection operator)
adds '

# how to prevent overfitting or underfitting
-1.cross validation
2.train with more data
3.remove features
4.early stoping
5.regularization
6.ensembling


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
m=100
x = np.random.rand(m,1)
y=0.5*x**2+x+2+np.random.randn(m,1)##ax*2+bx+c


In [6]:
print(x,y)

[[0.16653848]
 [0.97418673]
 [0.35944538]
 [0.98007019]
 [0.54693733]
 [0.48666708]
 [0.88162387]
 [0.47127169]
 [0.95348786]
 [0.34611276]
 [0.48546875]
 [0.40824562]
 [0.03190494]
 [0.4240277 ]
 [0.54302865]
 [0.41104658]
 [0.77727855]
 [0.04049266]
 [0.6748156 ]
 [0.73741144]
 [0.2573773 ]
 [0.2721747 ]
 [0.55460613]
 [0.85082856]
 [0.68550774]
 [0.60844826]
 [0.61185445]
 [0.14012958]
 [0.42507061]
 [0.35994386]
 [0.83942344]
 [0.25056511]
 [0.38814661]
 [0.87952481]
 [0.05601672]
 [0.39521539]
 [0.6104116 ]
 [0.36701421]
 [0.69771512]
 [0.90072632]
 [0.71065429]
 [0.50611647]
 [0.52004514]
 [0.89002495]
 [0.54820557]
 [0.58831771]
 [0.61048994]
 [0.35440744]
 [0.99315467]
 [0.28900848]
 [0.14053653]
 [0.06481584]
 [0.54408117]
 [0.40823864]
 [0.94022814]
 [0.97669698]
 [0.83818725]
 [0.76471879]
 [0.82002819]
 [0.41494218]
 [0.79756099]
 [0.99655403]
 [0.85273552]
 [0.97148514]
 [0.50546897]
 [0.65921905]
 [0.5427431 ]
 [0.35249357]
 [0.67147485]
 [0.34198805]
 [0.12167922]
 [0.32

In [7]:
print(x,"x values")
print(y,"y values")
print(m)

[[0.16653848]
 [0.97418673]
 [0.35944538]
 [0.98007019]
 [0.54693733]
 [0.48666708]
 [0.88162387]
 [0.47127169]
 [0.95348786]
 [0.34611276]
 [0.48546875]
 [0.40824562]
 [0.03190494]
 [0.4240277 ]
 [0.54302865]
 [0.41104658]
 [0.77727855]
 [0.04049266]
 [0.6748156 ]
 [0.73741144]
 [0.2573773 ]
 [0.2721747 ]
 [0.55460613]
 [0.85082856]
 [0.68550774]
 [0.60844826]
 [0.61185445]
 [0.14012958]
 [0.42507061]
 [0.35994386]
 [0.83942344]
 [0.25056511]
 [0.38814661]
 [0.87952481]
 [0.05601672]
 [0.39521539]
 [0.6104116 ]
 [0.36701421]
 [0.69771512]
 [0.90072632]
 [0.71065429]
 [0.50611647]
 [0.52004514]
 [0.89002495]
 [0.54820557]
 [0.58831771]
 [0.61048994]
 [0.35440744]
 [0.99315467]
 [0.28900848]
 [0.14053653]
 [0.06481584]
 [0.54408117]
 [0.40823864]
 [0.94022814]
 [0.97669698]
 [0.83818725]
 [0.76471879]
 [0.82002819]
 [0.41494218]
 [0.79756099]
 [0.99655403]
 [0.85273552]
 [0.97148514]
 [0.50546897]
 [0.65921905]
 [0.5427431 ]
 [0.35249357]
 [0.67147485]
 [0.34198805]
 [0.12167922]
 [0.32

In [8]:
x.shape

(100, 1)

In [9]:
y.shape

(100, 1)

In [10]:
from sklearn.linear_model import Ridge
rd=Ridge()

In [11]:
x[1]

array([0.97418673])

In [12]:
y[1]

array([2.35227861])

In [14]:
np.ndim(x)

2

In [15]:
rd.fit(x,y)

Ridge()

In [16]:
from sklearn.datasets import load_boston
bos_data=load_boston()

In [17]:
bos_data.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [18]:
df=pd.DataFrame(bos_data.data,columns=bos_data.feature_names)
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [19]:
df.shape

(506, 13)

In [20]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT'],
      dtype='object')

In [21]:
bos_data.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [22]:
df['landscape']=bos_data.target
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  landscape  
0     15.3  396.90   4.98       24.0  
1     17.8  396.90   9.14       21.6  
2     17.8  392.83   4.03       34.7  
3     18.7  394.63   2.94       33.4  
4     18.7  396.90   5.33       36.2

In [24]:
df.isnull().sum()

CRIM         0
ZN           0
INDUS        0
CHAS         0
NOX          0
RM           0
AGE          0
DIS          0
RAD          0
TAX          0
PTRATIO      0
B            0
LSTAT        0
landscape    0
dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   CRIM       506 non-null    float64
 1   ZN         506 non-null    float64
 2   INDUS      506 non-null    float64
 3   CHAS       506 non-null    float64
 4   NOX        506 non-null    float64
 5   RM         506 non-null    float64
 6   AGE        506 non-null    float64
 7   DIS        506 non-null    float64
 8   RAD        506 non-null    float64
 9   TAX        506 non-null    float64
 10  PTRATIO    506 non-null    float64
 11  B          506 non-null    float64
 12  LSTAT      506 non-null    float64
 13  landscape  506 non-null    float64
dtypes: float64(14)
memory usage: 55.4 KB


In [26]:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT   landscape  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [28]:
#separation of input and target features
x=df.iloc[::-1]
x

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   

     PTRATIO       B  LSTAT  landscape  
505     21.0  396.90   7.88       11.9  
504     21.0  393.45   6.48       22.0  
503     21.0  396.90   5.64       23.9  
502     21.0  396.90   9.08       20.6  
501     21.0  391.99   9.67       22.4  
..       ...     ...    ...        ...  
4       18.7  396.90   5.33       36.2  
3       18.7  394.63   2.94       33.4  
2       17.8  392.83   4.03       34.7  
1       17.8  396.90   9.14       21.6  
0       15.3  396.90   4.98       24.0  

[506 rows x 14 columns]

In [30]:
x=df.iloc[:,0:-1]
x

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [35]:
y = df['landscape']
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: landscape, Length: 506, dtype: float64

In [36]:
from sklearn.linear_model import LinearRegression
lin_alg=LinearRegression()

In [37]:
lin_alg.fit(x,y)

LinearRegression()

In [38]:
df.shape

(506, 14)

In [41]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state = 2)

In [42]:
lin_alg.score(x_train,y_train)

0.7320923327497029

In [43]:
lin_alg.score(x_test,y_test)

0.7638581703807343

In [45]:
from sklearn.linear_model import Lasso
la = Lasso(alpha = 100)

In [46]:
la.fit(x_train,y_train)

Lasso(alpha=100)

In [49]:
la.fit(x_test,y_test)

Lasso(alpha=100)

In [53]:
np.sum(la.coef_!=0)

2

In [54]:
np.sum(la.coef_==0)

11

In [56]:
bos_data.feature_names[la.coef_==0]

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'PTRATIO', 'LSTAT'], dtype='<U7')

In [57]:
bos_data.feature_names[la.coef_!=0]

array(['TAX', 'B'], dtype='<U7')

## KNN->K-Nearest Neighbour Classifier
- KNN is easy to implement
- Support Classification and Regression
- knn algorithm assumes that the similar things exists nearer to each other
### How does knn works
1. select k number of neighbours,i.e k=3,5
2. calculate the euclidien distance b/w data
3. assign the new data point to the majority nearest neighbours class


In [59]:
df=pd.read_csv("https://raw.githubusercontent.com/nagamounika5/Datasets/master/Tshirt_size.csv")
df

Height  Weight Shirt_Size
0      158      58          m
1      158      59          m
2      158      63          m
3      160      59          m
4      160      60          m
5      163      60          m
6      163      61          m
7      160      64          l
8      163      64          l
9      165      61          l
10     165      62          l
11     165      65          l
12     168      62          l
13     168      63          l
14     168      66          l
15     170      63          l
16     170      64          l
17     170      68          l

In [61]:
df.shape

(18, 3)

In [64]:
df.isnull().sum()

Height        0
Weight        0
Shirt_Size    0
dtype: int64

In [68]:
df.Shirt_Size.value_counts()

l    11
m     7
Name: Shirt_Size, dtype: int64

In [69]:
df.info

<bound method DataFrame.info of     Height  Weight Shirt_Size
0      158      58          m
1      158      59          m
2      158      63          m
3      160      59          m
4      160      60          m
5      163      60          m
6      163      61          m
7      160      64          l
8      163      64          l
9      165      61          l
10     165      62          l
11     165      65          l
12     168      62          l
13     168      63          l
14     168      66          l
15     170      63          l
16     170      64          l
17     170      68          l>

In [72]:
x = df[['Height','Weight']]
y = df['Shirt_Size']

In [76]:
from sklearn.neighbors import KNeighborsClassifier

In [77]:
knn = KNeighborsClassifier(n_neighbors=4)

In [82]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=4)

In [83]:
y_predict = knn.predict(x)

In [84]:
y_predict

array(['m', 'm', 'm', 'm', 'm', 'l', 'l', 'l', 'l', 'l', 'l', 'l', 'l',
       'l', 'l', 'l', 'l', 'l'], dtype=object)

In [85]:
y

0     m
1     m
2     m
3     m
4     m
5     m
6     m
7     l
8     l
9     l
10    l
11    l
12    l
13    l
14    l
15    l
16    l
17    l
Name: Shirt_Size, dtype: object

In [97]:
knn = KNeighborsClassifier(n_neighbors=5)

In [98]:
knn.fit(x,y)

KNeighborsClassifier()

In [99]:
y_predict = knn.predict(x)

In [100]:
y_predict

array(['m', 'm', 'm', 'm', 'm', 'm', 'l', 'm', 'l', 'l', 'l', 'l', 'l',
       'l', 'l', 'l', 'l', 'l'], dtype=object)

In [101]:
y

0     m
1     m
2     m
3     m
4     m
5     m
6     m
7     l
8     l
9     l
10    l
11    l
12    l
13    l
14    l
15    l
16    l
17    l
Name: Shirt_Size, dtype: object