#THIS IS  HEADING 1(H1 TAG)
##HEADING2(

In [4]:
import numpy as np

In [5]:
d1 = np.array([23,30,22,25])

In [6]:
d1.shape

(4,)

In [7]:
d1.size

4

In [8]:
d1[1]

30

In [9]:
d1[3]

25

In [10]:
d1[0:3]

array([23, 30, 22])

In [11]:
data = np.array(["name","30","CSE","D"])

In [12]:
data

array(['name', '30', 'CSE', 'D'], dtype='<U4')

In [13]:
import time

start_time=time.time()
list1=[x for x in range (1,100000)]
list2=[y for y in range (1,100000)]


op=list(map(lambda x,y :x*y,list1,list2))
end_time=time.time()

print("time taken by list operation",end_time-start_time)

time taken by list operation 0.020987510681152344


In [14]:
import time

start_time=time.time()
list1=[x for x in range (1,100000)]
list2=[y for y in range (1,100000)]


op=list(map(lambda x,y :x*y,list1,list2))
end_time=time.time()

print("time taken by list operation",end_time-start_time)


time taken by list operation 0.023985624313354492


In [15]:
import time

start_time=time.time()
list1=[x for x in range (1,100000)]
list2=[y for y in range (1,100000)]

op=list(map(lambda x,y :x*y,list1,list2))
end_time=time.time()

print("time taken by list operation",end_time-start_time)

time taken by list operation 0.03098320960998535


In [16]:
import time

start_time=time.time()
list1=[x for x in range (1,100000)]
list2=[y for y in range (1,100000)]

op=list(map(lambda x,y :x*y,list1,list2))
end_time=time.time()

print("time taken by list operation",end_time-start_time)

time taken by list operation 0.0239865779876709


In [17]:
import time

start_time=time.time()
list1=[x for x in range (1,100000)]
list2=[y for y in range (1,100000)]

op=list(map(lambda x,y :x*y,list1,list2))
end_time=time.time()

print("time taken by list operation",end_time-start_time)

time taken by list operation 0.02898383140563965


In [18]:
import time
start_time1=time.time()
ar1 = np.array(list1)
ar2 = np.array(list2)
ar1*ar2
end_time1=time.time()
print("time taken by numpy",end_time1-start_time1)

time taken by numpy 0.011991262435913086


In [19]:
# 2-D ARRAY DECLARATION
d2=np.array([[98,78,87],[89,96,95],[89,78,88]])
d2

array([[98, 78, 87],
       [89, 96, 95],
       [89, 78, 88]])

In [20]:
d2.shape

(3, 3)

In [21]:
d2.size

9

In [22]:
d2.ndim

2

In [23]:
d2

array([[98, 78, 87],
       [89, 96, 95],
       [89, 78, 88]])

In [24]:
d2[0]

array([98, 78, 87])

In [25]:
d2[2]

array([89, 78, 88])

In [26]:
d2[1:2]

array([[89, 96, 95]])

In [27]:
d2[0,2]

87

In [28]:
d2

array([[98, 78, 87],
       [89, 96, 95],
       [89, 78, 88]])

In [29]:
d2[1].max()

96

In [30]:
np.max(d2[0])

98

In [31]:
d2[:,2]

array([87, 95, 88])

In [32]:
d2[:,1].max()

96

In [33]:
d2[1].min()

89

In [34]:
np.min(d2[0])

78

In [35]:
d2[:,1].min()

78

In [36]:
d2[0].sum()

263

In [37]:
d2.sum()

798

In [38]:
d2[2].sum()

255

In [39]:
d2.sum(axis=0)

array([276, 252, 270])

In [40]:
d2.sum(axis=1)

array([263, 280, 255])

In [41]:
d3 = np.array([[[1,2,3],[6,7,8],
               [8,9,10],[10,11,12]]])

d3

array([[[ 1,  2,  3],
        [ 6,  7,  8],
        [ 8,  9, 10],
        [10, 11, 12]]])

In [42]:
d3[0]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [ 8,  9, 10],
       [10, 11, 12]])

In [43]:
d3[0,0]

array([1, 2, 3])

In [44]:
d3[0,1,2]

8

In [45]:
d3[0,3]

array([10, 11, 12])

In [46]:
range(1,10)

range(1, 10)

In [47]:
for i in range (1,11):
    print(i,end =" ")

1 2 3 4 5 6 7 8 9 10 

In [48]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(1,10,1.5)
    

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [50]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [51]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [52]:
# zero matrix
print(np.zeros([3,5]))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [53]:
np.ones([5,6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [54]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [55]:
np.tile(10,[5,5])

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [56]:
d21=np.array([[14,25,36,52],
              [24,51,65,15]])

In [57]:
d21

array([[14, 25, 36, 52],
       [24, 51, 65, 15]])

In [58]:
add_marks = np.tile(4,[2,4])
add_marks

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [59]:
final_marks = d21+add_marks
final_marks

array([[18, 29, 40, 56],
       [28, 55, 69, 19]])

In [60]:
mat = np.array([[1,10,10],[2,20,30],[30,2,28]])
mat

array([[ 1, 10, 10],
       [ 2, 20, 30],
       [30,  2, 28]])

In [61]:
np.linalg.inv(mat)

array([[ 0.16778523, -0.08724832,  0.03355705],
       [ 0.28322148, -0.09127517, -0.0033557 ],
       [-0.2       ,  0.1       , -0.        ]])

In [62]:
np.linalg.eig(mat)

(array([45.42493109+0.        j,  1.78753445+7.89983935j,
         1.78753445-7.89983935j]),
 array([[-0.30200348+0.        j,  0.30344165-0.31138643j,
          0.30344165+0.31138643j],
        [-0.73709533+0.        j,  0.73836508+0.        j,
          0.73836508-0.        j],
        [-0.60455304+0.        j, -0.46847773+0.21519128j,
         -0.46847773-0.21519128j]]))

In [63]:
np.random.random(10)

array([0.59897056, 0.34210774, 0.39813386, 0.97170402, 0.39592586,
       0.73195707, 0.10774717, 0.30970988, 0.53374289, 0.75623206])

In [64]:
np.random.randint(1,10)

3

In [65]:
np.random.randint(10)

7

In [66]:
np.random.randint(10,20)

18

In [70]:
np.random.randint(10,20,30)

array([11, 18, 18, 19, 12, 17, 11, 12, 16, 14, 11, 16, 19, 12, 17, 11, 18,
       11, 18, 14, 17, 14, 11, 19, 17, 13, 10, 10, 10, 12])

In [71]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [72]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [75]:
np.arange(13,21)

array([13, 14, 15, 16, 17, 18, 19, 20])

In [76]:
np.sin(90)

0.8939966636005579

In [77]:
np.tan(45)

1.6197751905438615

In [79]:
np.arcsin(1)

1.5707963267948966

In [80]:
array = np.arange(1,10).reshape(3,3)

In [81]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
array.max()

9

In [83]:
#finding the max value index
array.argmax()

8

In [84]:
#finding the min value index
array.argmin()

0

In [87]:
sec1=np.array(np.random.randint(10,20,[4,4]))
sec1

array([[18, 10, 15, 14],
       [19, 10, 13, 17],
       [12, 17, 12, 14],
       [12, 17, 16, 15]])

In [90]:
sec2=np.array(np.random.randint(1,10,[4,4]))
sec2

array([[2, 6, 6, 8],
       [2, 9, 4, 1],
       [3, 1, 9, 4],
       [9, 9, 7, 3]])

In [92]:
np.vstack([sec1,sec2])

array([[18, 10, 15, 14],
       [19, 10, 13, 17],
       [12, 17, 12, 14],
       [12, 17, 16, 15],
       [ 2,  6,  6,  8],
       [ 2,  9,  4,  1],
       [ 3,  1,  9,  4],
       [ 9,  9,  7,  3]])

In [93]:
np.hstack([sec1,sec2])

array([[18, 10, 15, 14,  2,  6,  6,  8],
       [19, 10, 13, 17,  2,  9,  4,  1],
       [12, 17, 12, 14,  3,  1,  9,  4],
       [12, 17, 16, 15,  9,  9,  7,  3]])

In [94]:
np.column_stack([sec1,sec2])

array([[18, 10, 15, 14,  2,  6,  6,  8],
       [19, 10, 13, 17,  2,  9,  4,  1],
       [12, 17, 12, 14,  3,  1,  9,  4],
       [12, 17, 16, 15,  9,  9,  7,  3]])

In [95]:
sec1+sec2

array([[20, 16, 21, 22],
       [21, 19, 17, 18],
       [15, 18, 21, 18],
       [21, 26, 23, 18]])

In [96]:
sec1*sec2

array([[ 36,  60,  90, 112],
       [ 38,  90,  52,  17],
       [ 36,  17, 108,  56],
       [108, 153, 112,  45]])

In [97]:
sec1@sec2

array([[227, 339, 381, 256],
       [250, 370, 390, 265],
       [220, 363, 346, 203],
       [241, 376, 389, 222]])

In [98]:
sec1%sec2

array([[0, 4, 3, 6],
       [1, 1, 1, 0],
       [0, 0, 3, 2],
       [3, 8, 2, 0]], dtype=int32)

In [102]:
sec1.dot(sec2)

array([[227, 339, 381, 256],
       [250, 370, 390, 265],
       [220, 363, 346, 203],
       [241, 376, 389, 222]])

In [104]:
sec1/sec2

array([[ 9.        ,  1.66666667,  2.5       ,  1.75      ],
       [ 9.5       ,  1.11111111,  3.25      , 17.        ],
       [ 4.        , 17.        ,  1.33333333,  3.5       ],
       [ 1.33333333,  1.88888889,  2.28571429,  5.        ]])

In [105]:
sec1-sec2

array([[16,  4,  9,  6],
       [17,  1,  9, 16],
       [ 9, 16,  3, 10],
       [ 3,  8,  9, 12]])

In [106]:
sec1^sec2

array([[16, 12,  9,  6],
       [17,  3,  9, 16],
       [15, 16,  5, 10],
       [ 5, 24, 23, 12]], dtype=int32)

In [107]:
sec1&sec2

array([[2, 2, 6, 8],
       [2, 8, 4, 1],
       [0, 1, 8, 4],
       [8, 1, 0, 3]], dtype=int32)

In [108]:
sec1//sec2

array([[ 9,  1,  2,  1],
       [ 9,  1,  3, 17],
       [ 4, 17,  1,  3],
       [ 1,  1,  2,  5]], dtype=int32)

In [110]:
sec1.transpose()

array([[18, 19, 12, 12],
       [10, 10, 17, 17],
       [15, 13, 12, 16],
       [14, 17, 14, 15]])

In [111]:
sec1.trace()

55

In [112]:
sec2.trace()

23

In [114]:
np.hsplit(sec1,2)

[array([[18, 10],
        [19, 10],
        [12, 17],
        [12, 17]]), array([[15, 14],
        [13, 17],
        [12, 14],
        [16, 15]])]

In [115]:
np.vsplit(sec1,2)

[array([[18, 10, 15, 14],
        [19, 10, 13, 17]]), array([[12, 17, 12, 14],
        [12, 17, 16, 15]])]

In [116]:
np.hsplit(sec1,[2,2])

[array([[18, 10],
        [19, 10],
        [12, 17],
        [12, 17]]), array([], shape=(4, 0), dtype=int32), array([[15, 14],
        [13, 17],
        [12, 14],
        [16, 15]])]

In [118]:
np.vsplit(sec1,[2,2])

[array([[18, 10, 15, 14],
        [19, 10, 13, 17]]),
 array([], shape=(0, 4), dtype=int32),
 array([[12, 17, 12, 14],
        [12, 17, 16, 15]])]

In [119]:
np.abs(100.25)

100.25

In [123]:
np.absolute(-100.25)

100.25

In [124]:
np.all(sec1>0)

True

In [126]:
np.any(sec1<0)

False

In [128]:
np.round(12.36)

12.0

In [131]:
np.ceil(10.23)

11.0