# this is heading1 (H1)
## H2
### H3 TAG


In [1]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [4]:
d1 = np.array([54,74,36,65,33,21])
d1

array([54, 74, 36, 65, 33, 21])

In [5]:
d1.shape

(6,)

In [6]:
d1.size

6

In [7]:
d1.ndim

1

In [8]:
d1

array([54, 74, 36, 65, 33, 21])

In [9]:
d1[3]

65

In [10]:
d1[0:3]

array([54, 74, 36])

In [11]:
data = np.array["ranga",123,"cse","A",45,65]
data

TypeError: 'builtin_function_or_method' object is not subscriptable

In [12]:
data = np.array(["ranga",123,"cse","A",45,65])
data

array(['ranga', '123', 'cse', 'A', '45', '65'], dtype='<U5')

In [40]:
import time

start_time = time.time()
list1 = [x for x in range (1,100000)]
list2 = [y for y in range (1,100000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time.time()

print("time taken by list concept",end_time-start_time)

time taken by list concept 0.031248092651367188


In [15]:
import time
list1 = [x for x in range (1,100000)]
list2 = [y for y in range (1,100000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time.time()
et-st

NameError: name 'et' is not defined

In [16]:
import time
list1 = [x for x in range (1,100000)]
list2 = [y for y in range (1,100000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time.time()
start_time = time.time()
print("time taken by list concept",end_time-start-time)

NameError: name 'start' is not defined

In [17]:
import time
list1 = [x for x in range (1,100000)]
list2 = [y for y in range (1,100000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time.time()

print("time taken by list concept",end_time-start-time)

NameError: name 'start' is not defined

In [18]:
import time
list1 = [x for x in range (1,100000)]
list2 = [y for y in range (1,100000)]

op = list(map(lambda x,y : x*y,list1,list2))
end_time = time.time()
start_time = time.time()
print("time taken by list concept",end_time-start-tiimport
      

SyntaxError: unexpected EOF while parsing (<ipython-input-18-d5f645f86c77>, line 9)

In [19]:
d2 = np.array([[43,56,54],[43,56,78]])
d2


array([[43, 56, 54],
       [43, 56, 78]])

In [20]:
d2.shape

(2, 3)

In [21]:
d2.size

6

In [22]:
d2.ndim

2

In [23]:
d2[0]

array([43, 56, 54])

In [24]:
d2[1]

array([43, 56, 78])

In [25]:
d2[4]

IndexError: index 4 is out of bounds for axis 0 with size 2

In [26]:
d2[1,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [27]:
d2[0,1]

56

In [28]:
d2

array([[43, 56, 54],
       [43, 56, 78]])

In [29]:
d2[1].max()

78

In [30]:
np.max(d2[1])

78

In [31]:
d2[:,2]

array([54, 78])

In [32]:
d2[:,1].max()

56

In [33]:
d2[:,0].min()

43

In [34]:
d2[0:2].sum()

330

In [35]:
d2[0].sum()

153

In [36]:
d2[0:1:2].sum()

153

In [37]:
d2.sum(axis=0)

array([ 86, 112, 132])

In [38]:
d2.sum(axis=1)

array([153, 177])

In [41]:
d3 = np.array([[1,3,2],[4,5,6],[7,8,9]])
d3

array([[1, 3, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
d3[0]

array([1, 3, 2])

In [43]:
d3[0,0]

1

In [44]:
d3{0,0}

SyntaxError: invalid syntax (<ipython-input-44-dd91a1267023>, line 1)

TypeError: 'numpy.ndarray' object is not callable

## range

# arrange()

In [46]:
range(1,10)

range(1, 10)

In [47]:
for i in range (1,11):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 

In [49]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
 np.arange( 1,10,0.5)
    

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [56]:
np.zeros([10,20])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [57]:
print(np.zeros([2,3]))

[[0. 0. 0.]
 [0. 0. 0.]]


In [60]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
np.tile(10,[3,3])

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [63]:
d21 = np.array([[14,45,36,41,52],[32,54,78,98,56]])
d21

array([[14, 45, 36, 41, 52],
       [32, 54, 78, 98, 56]])

In [64]:
add_marks = np.tile(5,[2,5])
add_marks

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [66]:
fina_marks = d21+add_marks
fina_marks

array([[ 19,  50,  41,  46,  57],
       [ 37,  59,  83, 103,  61]])

In [67]:
mat = np.array([[1,10,20],[2,45,65],[2,4,1]])
mat

array([[ 1, 10, 20],
       [ 2, 45, 65],
       [ 2,  4,  1]])

In [68]:
np.linalg.inv(mat)

array([[ 0.37391304, -0.12173913,  0.43478261],
       [-0.2226087 ,  0.06782609,  0.04347826],
       [ 0.1426087 , -0.02782609, -0.04347826]])

In [70]:
np.linalg.eig(mat)

(array([-6.09132532,  1.84190441, 51.24942091]),
 array([[ 0.56531373, -0.88829626, -0.22736711],
        [ 0.63997854,  0.39473649, -0.96998089],
        [-0.52043045, -0.23476127, -0.08626284]]))

# random

In [72]:
np.random.random(10)

array([0.98706338, 0.97371446, 0.02495515, 0.36518771, 0.30723897,
       0.66715107, 0.90677872, 0.86167762, 0.39495582, 0.11815965])

In [74]:
np.random.randint(10,20)

17

In [75]:
np.random.randint(10)

3

In [76]:
np.random.randint(10,20,30)

array([16, 16, 14, 18, 16, 14, 11, 15, 13, 10, 15, 15, 14, 16, 16, 14, 11,
       17, 12, 18, 15, 13, 19, 13, 14, 14, 13, 11, 15, 13])

In [78]:
np.random.randint(10,25,[4,6])

array([[16, 18, 21, 13, 15, 17],
       [14, 10, 18, 10, 13, 19],
       [21, 16, 23, 15, 24, 16],
       [14, 16, 10, 24, 24, 18]])

In [79]:
np.random.rand(10)

array([0.72577895, 0.04389415, 0.76059898, 0.71602263, 0.70220072,
       0.1724361 , 0.06288395, 0.39345592, 0.17545723, 0.75933895])

In [80]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [83]:
np.arange(1,49).reshape(4,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]]])

In [84]:
2,2,3,3

(2, 2, 3, 3)

In [85]:
2*2*3*3

36